askAI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auths.urls',  namespace = 'auths')),
    path('user/', include('user.urls',  namespace = 'user')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

auths/urls.py
from django.urls import path
from auths import views

app_name = 'auths'

urlpatterns = [
    path('', views.index, name='index'),
    path('authentication/', views.authentication, name='authentication'), 
    path('logout/', views.logout, name='logout'),   
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('upload/', views.upload_files, name='upload_files'),
    path('selectRepo/', views.select_repo, name='select_repo'),
    path('askQuestion/', views.ask_question, name='ask_question'),  
    path('send_answer/', views.send_answer, name='send_answer'),
]

auths/models.py
from django.db import models
# import datetime
# import os

# def filepath(request, filename):
#     old_filename = filename
#     timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
#     filename = "%s%s" % (timeNow, old_filename)
#     return os.path.join('profile/', filename)     


# Create your models here.
class userinfo(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)
    password = models.BinaryField()

    def __str__(self):
        return self.email

auths/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import *
from django.contrib import messages
import bcrypt
import csv


# Create your views here.
def index(request):
    return render (request, 'auths/authentication.html')

def authentication(request):
    if request.method == "POST":       
        name = request.POST.get('name')
        email = request.POST.get('email')
        passwd = request.POST.get('password')
        
        if name is not None:
            # Sign up
            # existing_users_psno = userinfo.objects.filter(psno = psno)
            existing_users_email = userinfo.objects.filter(email = email)
            if len(existing_users_email) != 0:
                messages.error(request, 'Email id already exists')
                return redirect('auths:index')
            else:
                password = passwd.encode('utf-8')    # the password to hash, encoded as bytes        
                salt = bcrypt.gensalt()   # generate a salt to add to the password before hashing        
                hashed_password = bcrypt.hashpw(password, salt)    # hash the password with the salt using the bcrypt hash function  
                        
                obj = userinfo(name = name, email = email, password = hashed_password) # Adding the new user to the database
                obj.save()
                
                # creating QnA csv for each new users
                file_name = "./media/user/QnA/"+email+".csv"
                with open(file_name, 'w', newline='') as csv_file:
                    csv_writer = csv.writer(csv_file)
                    # add header
                    csv_writer.writerow(['Question', 'Answer', 'Source', 'Page', 'Line'])
                    
                messages.success(request, 'Successfully Register')
                return redirect('auths:index')
                        
        else:
            # sign in
            curr_user = userinfo.objects.filter(email = email)
            # checking if the username exists or not in the database
            if len(curr_user) == 0:
                messages.error(request, 'Invalid Username')
                return redirect('auths:index')
            else:
                authenticated_user = check_pass(curr_user, passwd.encode('utf-8'))
                if authenticated_user is not None:
                    request.session['user_email'] = authenticated_user.email
                    messages.success(request, 'Logged in successfully')
                    return redirect('user:upload_files')
                else:
                    messages.error(request, 'Invalid Password')
                    return redirect('auths:index')
            
    else:  
        return redirect('auths:index')
    

def check_pass(curr_user, entered_passwd):
    '''This function will take the credentials given by the user and will check in the database.
    It will return the current user object if verified else None object.'''
    
    # if user is present in the database --> checks the password and then 
    if bcrypt.checkpw(entered_passwd, curr_user[0].password):
        return curr_user[0]


def logout(request):
    '''This function logs out the session of the current user
    And also deletes the current session'''
    user_email = request.session.get('user_email')
    # Deleting the session of the current user
    del request.session['user_email']
    messages.success(request, 'Logged Out')
    return redirect('auths:index')

templates/auths/authentication.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentication</title>
    <link href="{% static 'auths/css/authentication.css' %}" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'favicons/favicon.ico' %}"/>
    {% include '../messages/messages.html' %}
</head>

<body>

    <!-- SignUp page -->

    <div class="signInBox" id="signInBox">
        <span class="signInBorderLine"></span>
        <form action="{% url 'auths:authentication' %}" method="POST">
            {% csrf_token %}
            <h2>Sign In</h2>
            <div class="inputBox">
                <input name="email" type="email" required="required">
                <span>Username</span>
                <i></i>
            </div>
            <div class="inputBox">
                <input name="password" type="password" id="password" required="required">
                <span>Password</span>
                <i></i>
            </div>
            <div class="links">
                <input class="show_pass" id="passCheckbox" type="checkbox" onclick="showPassword()">
                <span class="show-password" onclick="showPassword()">Show Password </span>
            </div>
            <div class="links">
                <span>Don't have an account yet?</span>
                <a href="#" onclick="showSignUpTab()">SignUp</a>
            </div>
            <input type="submit" value="Login">
        </form>
    </div>

    <!-- SignUp page -->

    <div class="signUpBox" id="signUpBox">
        <span class="signUpBorderLine"></span>
        <form action="{% url 'auths:authentication' %}" method="POST">
            {% csrf_token %}
            <h2>Sign Up</h2>
            <div class="inputBox">
                <input name="name" type="text" required="required">
                <span>Name</span>
                <i></i>
            </div>
            <div class="inputBox">
                <input name="email" type="email" required="required">
                <span>Email Id</span>
                <i></i>
            </div>
            <div class="inputBox">
                <input name="password" type="password" id="signUpPassword" required="required">
                <span>Password</span>
                <i></i>
            </div>
            <div class="links">
                <input class="show_pass" id="signUpPassCheckbox" type="checkbox" onclick="showPassword()">
                <span class="show-password" onclick="showPassword()">Show Password </span>
            </div>
            <div class="links">
                <span>Already have an account?</span>
                <a href="#" onclick="showSignInTab()">SignIn</a>
            </div>
            <input id="btnSubmit" type="submit" value="Register">
        </form>
    </div>

    <!-- Add JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="{% static 'auths/js/authentication.js' %}"></script>
</body>

</html>