askAI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auths.urls',  namespace = 'auths')),
    path('user/', include('user.urls',  namespace = 'user')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

auths/urls.py
from django.urls import path
from auths import views

app_name = 'auths'

urlpatterns = [
    path('', views.index, name='index'),
    path('authentication/', views.authentication, name='authentication'), 
    path('logout/', views.logout, name='logout'),   
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('upload/', views.upload_files, name='upload_files'),
    path('selectRepo/', views.select_repo, name='select_repo'),
    path('askQuestion/', views.ask_question, name='ask_question'),  
    path('send_answer/', views.send_answer, name='send_answer'),
]

user/models.py
from django.db import models

user/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import *
from django.contrib import messages
import os, time
import pandas as pd
from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter, CharacterTextSplitter
from langchain.vectorstores import FAISS
from langchain.embeddings import SentenceTransformerEmbeddings
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM,AutoModelForCausalLM
from transformers import pipeline
import torch
import base64
import textwrap
from langchain.embeddings import SentenceTransformerEmbeddings
from langchain.llms import HuggingFacePipeline
from langchain.chains import RetrievalQA


# Global variable and models
# loading embedding model
embeddings = SentenceTransformerEmbeddings(model_name = "all-MiniLM-L6-v2")

checkpoint = '../libraries/ML_Model/LaMini-Flan-T5-783M'
# checkpoint = './libraries/ML_Model/LaMini-GPT-1.5B'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
base_model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint,device_map="auto",
                                              torch_dtype=torch.float32,offload_folder='offload_weights')

# Create your views here.
def upload_files(request):
    if request.session.get('user_email') is not None:
        if request.method == "POST":
            # Get a list of uploaded files using getlist
            uploaded_files = request.FILES.getlist('files')
            repo_type = request.POST.get('repoType')
            email = request.session.get('user_email')
            # Process each uploaded file
            
            # print("|"*50)
            # print(uploaded_files)
            
            try:
                for file in uploaded_files:
                    # print("|"*50)
                    # print(file)
                    text_splitter = RecursiveCharacterTextSplitter(
                        separators=["\n"],
                        chunk_size=300,
                        chunk_overlap=120,
                        length_function=len
                    )
                    with open('./media/uploadedFiles/' + file.name, 'wb+') as destination:
                                    for chunk in file.chunks():
                                        destination.write(chunk)
                    
                    loader = PyPDFLoader('./media/uploadedFiles/' + file.name)
                    pages = loader.load()
                    docs = text_splitter.split_documents(pages)
                    os.remove('./media/uploadedFiles/' + file.name)
                    
                    # comverting into db 
                    db = FAISS.from_documents(docs, embeddings)
                    
                    if repo_type == 'publicRepo':
                        # Handle each file here as needed
                        path = "./media/user/publicRepo/"
                        dir = os.listdir(path)
                        # Checking if the list is empty or not
                        if len(dir) == 0:
                            print('Creating The DB in public')
                            db.save_local('./media/user/publicRepo/publicDB')
                        else:
                            print('Merging The DB in public')
                            old_db = FAISS.load_local('./media/user/publicRepo/publicDB', embeddings)
                            old_db.merge_from(db)
                            old_db.save_local('./media/user/publicRepo/publicDB')                    
                    else:
                        # Handle each file here as needed
                        print('Creating The DB in private')
                        db.save_local('./media/user/privateRepo/' + email)

                messages.success(request, 'Successfully Uploaded! Please ask questions.')
                return redirect('user:upload_files')
            except Exception as e:
                print("|"*50)
                print("error while uploading the files: ", e)
                messages.error(request, 'Error! While uploading please try again.')
                return redirect('user:upload_files')
        return render(request, 'user/upload.html')
    else:
        return redirect('auths:index')

def select_repo(request):
    email = request.session.get('user_email')
    if request.session.get('user_email') is not None:
        if request.method=="POST":
            repo_type = request.POST.get("repotype")
            request.session['repo_type'] = repo_type
            if repo_type == 'publicRepo':
                # Handle each file here as needed
                path = "./media/user/publicRepo/"
                dir = os.listdir(path)
                # Checking if the list is empty or not
                if len(dir) == 0:
                    messages.error(request, 'Empty Repository! Please upload file.')
                    return redirect('user:upload_files')
                else:
                    return redirect('user:ask_question')
            else:
                try:
                    path = "./media/user/privateRepo/"+email+"/"
                    dir = os.listdir(path)
                    # Checking if the list is empty or not
                    if len(dir) == 0:
                        messages.error(request, 'Empty Repository! Please upload file.')
                        return redirect('user:upload_files')
                    else:
                        return redirect('user:ask_question')  
                except Exception as e:
                    messages.error(request, 'Empty Repository! Please upload file.')
                    return redirect('user:upload_files')
        return render(request, 'user/selectRepo.html')
    else:
        return redirect('auths:index')

def ask_question(request):
    if request.session.get('user_email') is not None:
        # load csv and send QnA to UI
        # Specify the path to your CSV file
        email = request.session.get('user_email')
        file_name = "./media/user/QnA/"+email+".csv"
        
        qna_df = pd.read_csv(file_name)
        ques_list = qna_df['Question'].tolist()
        ans_list = qna_df['Answer'].tolist()
        source_list = qna_df['Source'].tolist()
        page_list = qna_df['Page'].tolist()
        line_list = qna_df['Line'].tolist()
        qna_list = zip(ques_list, ans_list, source_list, page_list, line_list)
        
        if request.session.get('repo_type') == "privateRepo":
            repo_type = "Private Repository"
        else:
            repo_type = "Public Repository"
        context = {'qna_list' : qna_list, 'repo_type' : repo_type}
        return render(request, 'user/askQues.html', context)
    else:
        return redirect('auths:index')
    
def send_answer(request):
    if request.session.get('user_email') is not None:
        question = request.GET.get('question')
        email = request.session.get('user_email')

        # Get Anwser
        if request.session.get('repo_type') == "privateRepo":
            # answer = '''Sorry, I am in development phase.
            # You have selected private repository'''
            db_loc = './media/user/privateRepo/' + email
        else:
            # answer = '''Sorry, I am in development phase.
            # You have selected public repository'''
            db_loc = './media/user/publicRepo/publicDB'
        answer, generated_output = process_answer(question, db_loc)
        line = set()
        page = set()
        source = set()
        for i in range(len(generated_output['source_documents'])):
            a = generated_output['source_documents'][i].page_content.replace("\n", " ")
            a = a.replace("-\n", "")
            line.add(a)
            # line.add(x['source_documents'][i].page_content)
            source.add(generated_output['source_documents'][i].metadata['source'])
            page.add(str(generated_output['source_documents'][i].metadata['page']+1))

        save_line = "/\n/".join(line)
        save_page = "; ".join(page)
        save_source = "; ".join(source)
        ajax_line = "<br>".join(line)

        # Updating QnA in csv
        # Specify the path to your CSV file
        file_name = "./media/user/QnA/"+email+".csv"
        qna_df = pd.read_csv(file_name)
        
        # Check the number of rows
        if len(qna_df) < 10:
            # Add new data to the DataFrame
            new_row = pd.Series({'Question': question, 'Answer': answer, 'Source':save_source, 'Page':save_page, 'Line':save_line})
            qna_df = pd.concat([qna_df, new_row.to_frame().T], ignore_index=True)
        else:
            # Remove the 1st row and add new data to the 10th row
            qna_df = qna_df.iloc[1:]
            new_row = pd.Series({'Question': question, 'Answer': answer, 'Source':save_source, 'Page':save_page, 'Line':save_line})
            qna_df = pd.concat([qna_df, new_row.to_frame().T], ignore_index=True)
        # Write the modified DataFrame back to the CSV file
        qna_df.to_csv(file_name, index=False)
        
        # print('|'*100)
        # print(answer)
        # print('|'*100)
        # print(generated_output)
        # Sending answer to UI
        context = {
            'answer': answer,'source':save_source, 'page':save_page, 'line':ajax_line,
        }
        return JsonResponse(context)   
    else:
        return redirect('auths:index')
    


def llm_pipeline():
    pipe = pipeline(
        'text2text-generation',
        # 'text-generation',
        model=base_model,
        tokenizer=tokenizer,
        max_length = 512,
        do_sample=True,
        temperature=1.8,
        top_p=0.80,
        # repetition_penalty=1.2
    )
    local_llm = HuggingFacePipeline(pipeline=pipe)
    return local_llm

# @st.cache_resource
def qa_llm(db_loc):
    llm = llm_pipeline()
    db = FAISS.load_local(db_loc, embeddings)
    # retriever = db.as_retriever(search_type='similarity',k=4)    

templates/user/askQues.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ask Question</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'user/css/user.css' %}" rel="stylesheet">
    <link href="{% static 'user/css/askQues.css' %}" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'favicons/favicon.ico' %}"/>
    {% include '../messages/messages.html' %}
</head>

<body>
    <div class="page">
        <aside class="menu">
            <p class="logo">
                <img src="{% static 'user/img/askAI.png' %}">
                <span>AskAI
            </p>
            </p>
            <a href="{% url 'user:upload_files' %}" class="menu-item">
                <p class="material-icons icon">upload_file</p>
                <p class="text">Upload File</p>
            </a>
            <a href="{% url 'user:select_repo' %}" class="menu-item active">
                <p class="material-icons icon">question_answer</p>
                <p class="text">Ask Question</p>
            </a>
            <a href="{% url 'auths:logout' %}" class="menu-item bottom">
                <p class="material-icons icon">logout</p>
                <p class="text">Logout</p>
            </a>
        </aside>
    </div>
    <div class="main">
        <div class="mainHeading">
            <h2>Ask Question</h2>
            <span>{{repo_type}}</span>
            <a href="{% url 'user:select_repo' %}" class="formSubmit">Change Repository</a>
        </div>
        <div class="chatMainApps">
            <div class="chatApp">
                <div class="ChatWindow">
                    <div class="ChatItem ChatItem--expert-AI">
                        <div class="ChatItem-meta-AI">
                            <div class="ChatItem-avatar-AI"> <img class="ChatItem-avatarImage-AI"
                                    src="{% static 'user/img/askAI.png' %}" alt="AskAI">
                            </div>
                        </div>
                        <div class="ChatItem-chatContent-AI">
                            <div class="ChatItem-chatText-AI" style="margin-bottom: 10px;">Hi, I am AskAI. I am here to help you.
                            </div>
                        </div>
                    </div>
                    
                    {% for ques, ans, source, page_no, line in qna_list %}
                    <!-- Question -->
                    <div class="ChatItem ChatItem--expert">
                        <div class="ChatItem-meta">
                            <div class="ChatItem-avatar">
                                 <img class="ChatItem-avatarImage" src="{% static 'user/img/profile.jpg' %}" alt="User">
                            </div>
                        </div>
                        <div class="ChatItem-chatContent">
                                <div class="ChatItem-chatText">
                                    {{ques}} 
                                </div>
                        </div>
                    </div>
                    <!-- Answer -->    
                    <div class="ChatItem ChatItem--expert-AI">
                        <div class="ChatItem-meta-AI">
                            <div class="ChatItem-avatar-AI"> <img class="ChatItem-avatarImage-AI"
                                    src="{% static 'user/img/askAI.png' %}" alt="AskAI">
                            </div>
                        </div>
                        <div class="ChatItem-chatContent-AI">
                            <div class="ChatItem-chatText-AI">
                                {{ans}}
                            </div>
                            <div class="refBtn" onclick="showDiv(this)">Show Reference</div>
                            <div class="ChatItem-chatdetails-AI">
                                <div><span style="color: rgb(180, 180, 180); font-weight:700">Source:&nbsp;</span> 
                                    {{source}}
                                </div> 
                                <div><span style="color: rgb(180, 180, 180); font-weight:700">Page No:&nbsp;</span>
                                    {{page_no}}
                                </div> 
                                <div><span style="color: rgb(180, 180, 180); font-weight:700">Line:&nbsp;</span>
                                    {{line}}
                                </div>
                            </div>
                        </div>
                    </div>                
                    {% endfor %}

                </div>
                <div class="ChatInput is-hidey">
                    <div class="ChatInput-input" contenteditable="true" placeholder="Type your question here..."></div>
                    <div class="ChatLoading"><span class="loader"></span></div>
                </div>
            </div>
        </div>
    </div>


    <!-- Add JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="{% static 'user/js/user.js' %}"></script>
    <script src="{% static 'user/js/askQues.js' %}"></script>
</body>

</html>

templates/user/selectRepo.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Select Repository</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'user/css/user.css' %}" rel="stylesheet">
    <link href="{% static 'user/css/selectRepo.css' %}" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'favicons/favicon.ico' %}"/>
    {% include '../messages/messages.html' %}
</head>

<body>
    <div class="page">
        <aside class="menu">
            <p class="logo">
                <img src="{% static 'user/img/askAI.png' %}">
                <span>AskAI
            </p>
            </p>
            <a href="{% url 'user:upload_files' %}" class="menu-item">
                <p class="material-icons icon">upload_file</p>
                <p class="text">Upload File</p>
            </a>
            <a href="{% url 'user:select_repo' %}" class="menu-item active">
                <p class="material-icons icon">question_answer</p>
                <p class="text">Ask Question</p>
            </a>
            <a href="{% url 'auths:logout' %}" class="menu-item bottom">
                <p class="material-icons icon">logout</p>
                <p class="text">Logout</p>
            </a>
        </aside>
    </div>
    <div class="main">
        <div class="mainHeading">
            <h2>Ask Question</h2>
        </div>
        <div class="selectRepo">            
            <h1>Select Repository for Question Answer</h1>
        </div>
        <div class="selectRepo">
            <div class="repo">
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" value="publicRepo" name="repotype" style="display: none;">
                    <input class="formSubmit" type="submit" value="Public Repository">
                </form>
            </div>
            <div class="repo">
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" value="privateRepo" name="repotype" style="display: none;">
                    <input class="formSubmit" type="submit" value="Private Repository">
                </form>
            </div>
        </div>
    </div>


    <!-- Add JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
    <script src="{% static 'user/js/user.js' %}"></script>
    <script src="{% static 'user/js/selectRepo.js' %}"></script>
</body>

</html>

templates/user/upload.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'user/css/user.css' %}" rel="stylesheet">
    <link href="{% static 'user/css/upload.css' %}" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'favicons/favicon.ico' %}"/>
    {% include '../messages/messages.html' %}
</head>

<body>
    <div class="page">
        <aside class="menu">
            <p class="logo">
                <img src="{% static 'user/img/askAI.png' %}">
                <span>AskAI
            </p>
            </p>
            <a href="{% url 'user:upload_files' %}" class="menu-item active">
                <p class="material-icons icon">upload_file</p>
                <p class="text">Upload File</p>
            </a>
            <a href="{% url 'user:select_repo' %}" class="menu-item">
                <p class="material-icons icon">question_answer</p>
                <p class="text">Ask Question</p>
            </a>
            <a href="{% url 'auths:logout' %}" class="menu-item bottom">
                <p class="material-icons icon">logout</p>
                <p class="text">Logout</p>
            </a>
        </aside>
    </div>
    <div class="main">
        <div class="mainHeading">
            <h2>Upload File</h2>
        </div>
        <div class="mainApps">
            <div class="app">
                <div class="box">
                    <h1>Drag & Drop Files to Upload</h1>
                    <form enctype="multipart/form-data" method="POST" id="uploadForm">
                      {% csrf_token %}
                        <div class="select">
                            <select id="modelDropdown" name="repoType" id="Customer" required>
                                <option value="" selected disabled hidden>Select Repository</option>
                                <option value="publicRepo">
                                    Public Repository</option>
                                <option value="privateRepo">
                                    Private Repository</option>
                            </select>
                        </div>
                        <input class="demo1" type="file" multiple placeholder="Select Files" name="files"
                        accept=".pdf" />
                        <br>
                        <!-- <input id="demo2" class="demo1" type="file" data_btn_text="Browse"
                            placeholder="drage and drop file here" name="file" />
                        <br> -->
                        <input class="formSubmit" type="submit" value="Upload" />
                    </form>
                </div>
            </div>
        </div>
    </div>


    <!-- loader  -->
    <div class="loaderMain">
        <div class="loading">
            <span class="uploading"></span>
        </div>
        <div class="loadingTextCenter">
            <span class="loader">Uploading</span>
        </div>
    </div>


    <!-- Add JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
    <script src="{% static 'user/js/user.js' %}"></script>
    <script src="{% static 'user/js/upload.js' %}"></script>
</body>

</html>